fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
  - repo: https://github.com/MarcoGorelli/madforhooks
    rev: 0.4.1
    hooks:
      - id: no-print-statements

